# Generated by Django 5.0.6 on 2024-07-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
