# Generated by Django 5.0.6 on 2024-08-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Pre-KG', 'Pre-KG'), ('UKG', 'UKG'), ('LKG', 'LKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=777, max_length=6),
            preserve_default=False,
        ),
    ]
