# Generated by Django 5.1.2 on 2024-10-10 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_createdat_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 15, 52, 14, 105270), verbose_name=datetime.datetime.now),
        ),
    ]
