# Generated by Django 5.1.2 on 2024-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_createdat_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.BooleanField(choices=[(True, 'SuperUser'), (False, 'Staff')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
