# Generated by Django 5.0.3 on 2024-03-31 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(4)]),
            preserve_default=False,
        ),
    ]
